// Comprehensive Mock Data for MediConnect Platform

export const mockUsers = [
  {
    id: '1',
    name: 'Dr. Sarah Anderson',
    role: 'Faculty',
    college: 'AIIMS Delhi',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sarah',
    bio: 'Assistant Professor of Anatomy | Research enthusiast',
    badge: 'Verified Faculty',
    followers: 2450,
    following: 180,
    reputation: 4850,
    specialty: 'Anatomy',
    verified: true,
  },
  {
    id: '2',
    name: 'Rajesh Kumar',
    role: 'Student',
    college: 'CMC Vellore',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajesh',
    bio: '3rd year MBBS | NEET PG aspirant | Cricket lover',
    followers: 320,
    following: 450,
    reputation: 1850,
    year: '3rd Year',
    verified: false,
  },
  {
    id: '3',
    name: 'Dr. Priya Sharma',
    role: 'Doctor',
    college: 'AIIMS Mumbai',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Priya',
    bio: 'Senior Resident in Cardiology | Mentor for NEET PG',
    followers: 1200,
    following: 280,
    reputation: 3420,
    specialty: 'Cardiology',
    verified: true,
  },
  {
    id: '4',
    name: 'Aditya Patel',
    role: 'Student',
    college: 'Delhi Medical College',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Aditya',
    bio: '4th year MBBS | Content creator | Basketball enthusiast',
    followers: 580,
    following: 320,
    reputation: 2150,
    year: '4th Year',
    verified: true,
  },
  {
    id: '5',
    name: 'Dr. Vikram Gupta',
    role: 'Faculty',
    college: 'JIPMER Puducherry',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Vikram',
    bio: 'Professor of Pathology | Educational content creator',
    followers: 3200,
    following: 150,
    reputation: 5670,
    specialty: 'Pathology',
    verified: true,
  },
];

export const mockCommunities = [
  {
    id: 'c1',
    name: 'NEET PG Preparation',
    description: 'Comprehensive guide for NEET PG aspirants with study material, discussion, and tips',
    members: 12500,
    posts: 2345,
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=NEETPG',
    banner: '#0D9488',
    founder: 'Dr. Vikram Gupta',
    joinedStatus: true,
    rules: [
      'Be respectful to all members',
      'No spam or promotional content',
      'Share verified information only',
    ],
  },
  {
    id: 'c2',
    name: 'Anatomy Masters',
    description: 'For anatomy enthusiasts - discussions on anatomy concepts, clinical correlations, and case studies',
    members: 8900,
    posts: 1560,
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=ANAT',
    banner: '#14B8A6',
    founder: 'Dr. Sarah Anderson',
    joinedStatus: false,
    rules: [
      'Focus on anatomy concepts',
      'Share high-quality diagrams',
    ],
  },
  {
    id: 'c3',
    name: 'Cardiology Corner',
    description: 'Dedicated to cardiology learners - ECG interpretation, pathophysiology, and clinical cases',
    members: 5600,
    posts: 890,
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=CARDIO',
    banner: '#DC2626',
    founder: 'Dr. Priya Sharma',
    joinedStatus: true,
    rules: [
      'ECG cases welcome',
      'Clinical correlation required',
    ],
  },
  {
    id: 'c4',
    name: 'Research & Publications',
    description: 'Share and discuss research findings, publications, and career growth in medical research',
    members: 3400,
    posts: 450,
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=RESEARCH',
    banner: '#0284C7',
    founder: 'Dr. Vikram Gupta',
    joinedStatus: true,
    rules: [
      'Original research only',
      'Peer-reviewed articles preferred',
    ],
  },
  {
    id: 'c5',
    name: 'MBBS 3rd Year Study Group',
    description: 'For 3rd year MBBS students - class materials, exam discussions, and study schedules',
    members: 2100,
    posts: 678,
    avatar: 'https://api.dicebear.com/7.x/initials/svg?seed=MBBS3',
    banner: '#F59E0B',
    founder: 'Rajesh Kumar',
    joinedStatus: true,
    rules: [
      'Share study materials',
      'Discuss exam preparations',
    ],
  },
];

export const mockPosts = [
  {
    id: 'p1',
    author: mockUsers[0],
    type: 'text',
    title: 'Understanding Cardiac Action Potential',
    content: 'The cardiac action potential consists of 5 phases. Let me break down each phase and its clinical significance. Phase 0 is rapid depolarization, Phase 1 is early repolarization, Phase 2 is the plateau, Phase 3 is rapid repolarization, and Phase 4 is the resting membrane potential. Understanding this is crucial for ECG interpretation!',
    timestamp: '2 hours ago',
    likes: 1230,
    comments: 230,
    tags: ['Cardiology', 'Physiology', 'Educational'],
    community: mockCommunities[0],
    liked: false,
    saved: false,
    image: null,
    video: null,
  },
  {
    id: 'p2',
    author: mockUsers[1],
    type: 'image',
    title: 'ECG Case Study: Normal vs Abnormal',
    content: 'Here\'s a comparison of normal and abnormal ECG patterns. Can you spot the differences? Great resource for learning ECG interpretation!',
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=500&h=400',
    timestamp: '4 hours ago',
    likes: 420,
    comments: 85,
    tags: ['Cardiology', 'Diagnostic', 'ECG'],
    community: mockCommunities[0],
    liked: true,
    saved: false,
    video: null,
  },
  {
    id: 'p3',
    author: mockUsers[3],
    type: 'video',
    title: 'Anatomy Quick Lesson: Coronary Circulation',
    content: 'A detailed video explanation of coronary artery anatomy and blood supply to different parts of the heart. Essential for cardiology understanding!',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    videoThumbnail: 'https://images.unsplash.com/photo-1584308666744-24d5f400f6f6?w=500&h=300',
    duration: '12:45',
    timestamp: '6 hours ago',
    likes: 890,
    comments: 250,
    tags: ['Anatomy', 'Video Lesson', 'Cardiology'],
    community: mockCommunities[1],
    liked: true,
    saved: false,
  },
  {
    id: 'p4',
    author: mockUsers[1],
    type: 'discussion',
    title: 'Case Discussion: Acute Abdomen',
    content: 'A 35-year-old male presents with acute onset epigastric pain radiating to the back. What\'s your differential diagnosis? Patient also has elevated lipase. Discuss!',
    timestamp: '8 hours ago',
    likes: 620,
    comments: 200,
    tags: ['Surgery', 'Case Study', 'Clinical'],
    community: mockCommunities[0],
    liked: false,
    saved: true,
    image: null,
    video: null,
  },
  {
    id: 'p5',
    author: mockUsers[4],
    type: 'course',
    title: 'New Course: Pathology Fundamentals',
    content: 'Just launched my new course on clinical pathology with real case studies. Video-based learning with practice questions. Limited time discount!',
    courseId: 'course4',
    courseName: 'Clinical Pathology: Case-Based Learning',
    courseImage: '🔬',
    timestamp: '10 hours ago',
    likes: 2370,
    comments: 450,
    tags: ['Pathology', 'Course', 'Learning'],
    community: mockCommunities[0],
    liked: false,
    saved: false,
  },
  {
    id: 'p6',
    author: mockUsers[2],
    type: 'image',
    title: 'Cardiac Histology: Myocardial Structure',
    content: 'Beautiful histological slides of cardiac myocytes showing the sarcomere structure. Important for understanding cardiac physiology!',
    imageUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&h=400',
    timestamp: '12 hours ago',
    likes: 540,
    comments: 120,
    tags: ['Histology', 'Cardiology', 'Educational'],
    community: mockCommunities[1],
    liked: false,
    saved: false,
    video: null,
  },
  {
    id: 'p7',
    author: mockUsers[0],
    type: 'text',
    title: 'Tips for NEET PG Success: Time Management',
    content: 'Based on my experience helping students prepare for NEET PG, here are key time management strategies: 1) Divide your schedule into focused 90-minute blocks, 2) Allocate 60% time for theory and 40% for practice, 3) Review previous day\'s topics daily, 4) Take a mock test every week.',
    timestamp: '14 hours ago',
    likes: 1840,
    comments: 380,
    tags: ['NEET PG', 'Tips', 'Study Strategy'],
    community: mockCommunities[2],
    liked: true,
    saved: true,
    image: null,
    video: null,
  },
  {
    id: 'p8',
    author: mockUsers[3],
    type: 'video',
    title: 'Clinical Examination: Cardiac Auscultation',
    content: 'Step-by-step guide to cardiac auscultation with real patient demonstrations. Learn how to identify different heart sounds and murmurs!',
    videoUrl: 'https://www.youtube.com/embed/dQw4w9WgXcQ',
    videoThumbnail: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=500&h=300',
    duration: '18:32',
    timestamp: '16 hours ago',
    likes: 1200,
    comments: 340,
    tags: ['Clinical Skills', 'Examination', 'Video'],
    community: mockCommunities[0],
    liked: false,
    saved: false,
  },
  {
    id: 'p9',
    author: mockUsers[4],
    type: 'text',
    title: 'Pathology MCQ Discussion: Tumor Classification',
    content: 'Let\'s discuss the TNM staging system and WHO classification of tumors. These are commonly asked in exams. Feel free to ask questions in comments!',
    timestamp: '18 hours ago',
    likes: 680,
    comments: 195,
    tags: ['Pathology', 'MCQ', 'Oncology'],
    community: mockCommunities[0],
    liked: true,
    saved: false,
    image: null,
    video: null,
  },
  {
    id: 'p10',
    author: mockUsers[1],
    type: 'image',
    title: 'Pharmacology Concept Map: ACE Inhibitors',
    content: 'Created this concept map showing the mechanism of action and clinical uses of ACE inhibitors. Hope this helps in your preparation!',
    imageUrl: 'https://images.unsplash.com/photo-1584308666744-24d5f400f6f6?w=500&h=400',
    timestamp: '20 hours ago',
    likes: 920,
    comments: 210,
    tags: ['Pharmacology', 'Concept Map', 'Visual Learning'],
    community: mockCommunities[0],
    liked: false,
    saved: true,
    video: null,
  },
];

export const mockQuizzes = [
  {
    id: 'q1',
    title: 'Daily Challenge: Anatomy Basics',
    category: 'Anatomy',
    difficulty: 'Easy',
    questions: 10,
    duration: 15,
    avgScore: 72,
    participants: 3450,
    points: 100,
    streak: true,
    completed: true,
    userScore: 90,
  },
  {
    id: 'q2',
    title: 'Cardiology: ECG Interpretation',
    category: 'Cardiology',
    difficulty: 'Hard',
    questions: 25,
    duration: 45,
    avgScore: 58,
    participants: 1200,
    points: 250,
    streak: false,
    completed: false,
    userScore: null,
  },
  {
    id: 'q3',
    title: 'Biochemistry: Metabolic Pathways',
    category: 'Biochemistry',
    difficulty: 'Medium',
    questions: 20,
    duration: 30,
    avgScore: 65,
    participants: 2100,
    points: 150,
    streak: false,
    completed: true,
    userScore: 75,
  },
  {
    id: 'q4',
    title: 'Pharmacology: Drug Interactions',
    category: 'Pharmacology',
    difficulty: 'Medium',
    questions: 15,
    duration: 25,
    avgScore: 62,
    participants: 980,
    points: 120,
    streak: true,
    completed: true,
    userScore: 80,
  },
  {
    id: 'q5',
    title: 'NEET PG Mock: Complete Test',
    category: 'NEET PG',
    difficulty: 'Hard',
    questions: 300,
    duration: 360,
    avgScore: 52,
    participants: 5600,
    points: 500,
    streak: false,
    completed: false,
    userScore: null,
  },
];

export const mockCourses = [
  {
    id: 'course1',
    title: 'Complete NEET PG 2025 Preparation',
    instructor: 'Dr. Vikram Gupta',
    instructorAvatar: '👨‍🏫',
    category: 'NEET PG',
    rating: 4.8,
    reviews: 1240,
    students: 5600,
    duration: '180 hours',
    level: 'Advanced',
    price: 4999,
    isPaid: true,
    image: '📚',
    lessons: 45,
    progress: 65,
    enrolled: true,
    description: 'Comprehensive NEET PG preparation covering all subjects with video lectures, practice questions, and mock tests',
    thumbnail: '📚',
    modules: [
      {
        id: 'mod-1',
        title: 'Internal Medicine Basics',
        lessons: [
          { id: 'l-1', title: 'Cardiovascular System', duration: '45 min', videoUrl: 'https://example.com/video1.mp4', completed: true },
          { id: 'l-2', title: 'Respiratory System', duration: '38 min', videoUrl: 'https://example.com/video2.mp4', completed: true },
          { id: 'l-3', title: 'GIT System', duration: '42 min', videoUrl: 'https://example.com/video3.mp4', completed: false },
        ]
      },
      {
        id: 'mod-2',
        title: 'Surgery Essentials',
        lessons: [
          { id: 'l-4', title: 'General Surgery Basics', duration: '50 min', videoUrl: 'https://example.com/video4.mp4', completed: false },
        ]
      }
    ]
  },
  {
    id: 'course2',
    title: 'Anatomy for Clinical Practice',
    instructor: 'Dr. Sarah Anderson',
    instructorAvatar: '👩‍🏫',
    category: 'Anatomy',
    rating: 4.9,
    reviews: 890,
    students: 3200,
    duration: '90 hours',
    level: 'Intermediate',
    price: 0,
    isPaid: false,
    image: '🦴',
    lessons: 28,
    progress: 0,
    enrolled: false,
    description: 'Master clinical anatomy with 3D models, cadaver dissections, and clinical correlations for better patient understanding',
    thumbnail: '🦴',
    modules: []
  },
  {
    id: 'course3',
    title: 'ECG Interpretation Masterclass',
    instructor: 'Dr. Priya Sharma',
    instructorAvatar: '👩‍🏫',
    category: 'Cardiology',
    rating: 4.7,
    reviews: 560,
    students: 2100,
    duration: '45 hours',
    level: 'Intermediate',
    price: 1999,
    isPaid: true,
    image: '🫀',
    lessons: 18,
    progress: 40,
    enrolled: true,
    description: 'Learn ECG interpretation from basics to advanced with real patient case studies and interactive quizzes',
    thumbnail: '🫀',
    modules: []
  },
  {
    id: 'course4',
    title: 'Clinical Pathology: Case-Based Learning',
    instructor: 'Dr. Vikram Gupta',
    instructorAvatar: '👨‍🏫',
    category: 'Pathology',
    rating: 4.6,
    reviews: 420,
    students: 1800,
    duration: '60 hours',
    level: 'Intermediate',
    price: 2499,
    isPaid: true,
    image: '🔬',
    lessons: 24,
    progress: 0,
    enrolled: false,
    description: 'Understanding pathology through real laboratory cases, histopathology, and diagnostic approaches',
    thumbnail: '🔬',
    modules: []
  },
  {
    id: 'course5',
    title: 'Pharmacology Essentials',
    instructor: 'Dr. Vikram Gupta',
    instructorAvatar: '👨‍🏫',
    category: 'Pharmacology',
    rating: 4.5,
    reviews: 320,
    students: 1200,
    duration: '75 hours',
    level: 'Intermediate',
    price: 0,
    isPaid: false,
    image: '💊',
    lessons: 30,
    progress: 0,
    enrolled: false,
    description: 'Learn drug mechanisms, interactions, and clinical applications with memory tricks and mnemonics',
    thumbnail: '💊',
    modules: []
  },
];

export const mockNotes = [
  {
    id: 'note1',
    title: 'Anatomy Revision: Cardiovascular System',
    author: 'Dr. Sarah Anderson',
    subject: 'Anatomy',
    pages: 45,
    downloads: 2300,
    rating: 4.7,
    uploadDate: '1 week ago',
    format: 'PDF',
    size: '12 MB',
    saved: true,
  },
  {
    id: 'note2',
    title: 'NEET PG Biochemistry Short Notes',
    author: 'Rajesh Kumar',
    subject: 'Biochemistry',
    pages: 78,
    downloads: 4100,
    rating: 4.8,
    uploadDate: '2 weeks ago',
    format: 'PDF',
    size: '18 MB',
    saved: false,
  },
  {
    id: 'note3',
    title: 'Pharmacology: Drug Mnemonics & Charts',
    author: 'Aditya Patel',
    subject: 'Pharmacology',
    pages: 34,
    downloads: 3200,
    rating: 4.6,
    uploadDate: '3 weeks ago',
    format: 'PDF',
    size: '8 MB',
    saved: true,
  },
  {
    id: 'note4',
    title: 'Surgery Important Procedures Guide',
    author: 'Dr. Priya Sharma',
    subject: 'Surgery',
    pages: 56,
    downloads: 1800,
    rating: 4.5,
    uploadDate: '1 month ago',
    format: 'PDF',
    size: '14 MB',
    saved: false,
  },
];

export const mockOpportunities = [
  {
    id: 'opp1',
    title: 'Summer Internship: Cardiology Department',
    organization: 'AIIMS Delhi',
    type: 'Internship',
    location: 'New Delhi',
    duration: '3 months',
    stipend: '₹15,000/month',
    applications: 234,
    deadline: '2025-05-30',
    description: 'Hands-on experience in cardiology with mentorship from senior faculty',
    featured: true,
  },
  {
    id: 'opp2',
    title: 'Research Fellowship: Biochemistry Lab',
    organization: 'CMC Vellore',
    type: 'Research',
    location: 'Vellore',
    duration: '6 months',
    stipend: 'Unpaid',
    applications: 89,
    deadline: '2025-06-15',
    description: 'Opportunity to work on metabolic research projects',
    featured: false,
  },
  {
    id: 'opp3',
    title: 'Resident Doctor Position',
    organization: 'Government Medical College',
    type: 'Residency',
    location: 'Multiple Locations',
    duration: '3 years',
    stipend: '₹45,000/month',
    applications: 5600,
    deadline: '2025-07-01',
    description: 'Competitive residency program in various specialties',
    featured: true,
  },
  {
    id: 'opp4',
    title: 'Teaching Assistant: Anatomy',
    organization: 'JIPMER Puducherry',
    type: 'Teaching',
    location: 'Puducherry',
    duration: '1 year',
    stipend: '₹25,000/month',
    applications: 156,
    deadline: '2025-05-15',
    description: 'Support faculty in delivering anatomy lectures and practicals',
    featured: false,
  },
];

export const leaderboardData = [
  { rank: 1, user: 'Dr. Vikram Gupta', points: 45230, streak: 128, level: 'Expert' },
  { rank: 2, user: 'Rajesh Kumar', points: 38900, streak: 95, level: 'Intermediate' },
  { rank: 3, user: 'Dr. Priya Sharma', points: 36450, streak: 87, level: 'Advanced' },
  { rank: 4, user: 'Aditya Patel', points: 32100, streak: 72, level: 'Intermediate' },
  { rank: 5, user: 'Dr. Sarah Anderson', points: 28760, streak: 65, level: 'Advanced' },
  { rank: 6, user: 'Neha Singh', points: 25430, streak: 58, level: 'Beginner' },
  { rank: 7, user: 'Rohit Sharma', points: 23120, streak: 45, level: 'Beginner' },
  { rank: 8, user: 'Priya Kapoor', points: 20890, streak: 38, level: 'Beginner' },
];

export const mockLiveClasses = [
  {
    id: 'live-1',
    title: 'Cardiology: ECG Case Discussion Live',
    instructor: 'Dr. Priya Sharma',
    instructorAvatar: '👩‍🏫',
    category: 'Cardiology',
    topic: 'ECG Interpretation',
    scheduledTime: new Date(Date.now() + 2 * 60 * 60 * 1000).toISOString(),
    duration: 60,
    participants: 234,
    isLive: false,
    recordingUrl: null,
    status: 'scheduled',
    description: 'Interactive session discussing real cardiology cases and ECG interpretations',
  },
  {
    id: 'live-2',
    title: 'NEET PG Strategy Discussion',
    instructor: 'Dr. Vikram Gupta',
    instructorAvatar: '👨‍🏫',
    category: 'NEET PG',
    topic: 'Exam Preparation',
    scheduledTime: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    duration: 90,
    participants: 567,
    isLive: true,
    recordingUrl: null,
    status: 'live',
    description: 'Live Q&A session with NEET PG toppers and discussion of preparation strategies',
  },
  {
    id: 'live-3',
    title: 'Anatomy: 3D Model Workshop',
    instructor: 'Dr. Sarah Anderson',
    instructorAvatar: '👩‍🏫',
    category: 'Anatomy',
    topic: 'Cardiovascular Anatomy',
    scheduledTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    duration: 75,
    participants: 342,
    isLive: false,
    recordingUrl: 'https://example.com/recordings/anatomy-workshop-1.mp4',
    status: 'completed',
    description: 'Recorded workshop on 3D anatomical models and clinical correlations',
  },
];

export const mockPayments = [
  {
    id: 'pay-1',
    courseId: 'course1',
    courseName: 'Complete NEET PG 2025 Preparation',
    amount: 4999,
    status: 'completed',
    date: '2024-01-10',
    paymentMethod: 'Card',
    transactionId: 'TXN12345',
  },
  {
    id: 'pay-2',
    courseId: 'course3',
    courseName: 'ECG Interpretation Masterclass',
    amount: 1999,
    status: 'completed',
    date: '2024-01-05',
    paymentMethod: 'UPI',
    transactionId: 'TXN12346',
  },
];

export const mockAnalytics = {
  learningTime: [
    { day: 'Mon', hours: 2.5 },
    { day: 'Tue', hours: 3.2 },
    { day: 'Wed', hours: 1.8 },
    { day: 'Thu', hours: 4.1 },
    { day: 'Fri', hours: 2.9 },
    { day: 'Sat', hours: 5.3 },
    { day: 'Sun', hours: 3.0 },
  ],
  quizPerformance: [
    { subject: 'Cardiology', accuracy: 82 },
    { subject: 'Anatomy', accuracy: 78 },
    { subject: 'Pathology', accuracy: 85 },
    { subject: 'Pharmacology', accuracy: 72 },
    { subject: 'Biochemistry', accuracy: 88 },
  ],
  courseProgress: [
    { course: 'NEET PG', completion: 65 },
    { course: 'ECG Masterclass', completion: 40 },
  ],
};

export const mockTrendingTopics = [
  { id: 't1', title: 'NEET PG 2025', posts: 12450, trend: '+240%', image: '📚' },
  { id: 't2', title: 'Cardiology Basics', posts: 8320, trend: '+180%', image: '🫀' },
  { id: 't3', title: 'Clinical Case Discussion', posts: 6890, trend: '+145%', image: '🏥' },
  { id: 't4', title: 'Anatomy 3D Models', posts: 5670, trend: '+120%', image: '🦴' },
  { id: 't5', title: 'Pharmacology MCQ', posts: 4230, trend: '+95%', image: '💊' },
  { id: 't6', title: 'Pathology Concepts', posts: 3890, trend: '+85%', image: '🔬' },
  { id: 't7', title: 'ECG Interpretation', posts: 3450, trend: '+75%', image: '📊' },
  { id: 't8', title: 'Surgery Case Studies', posts: 2890, trend: '+65%', image: '⚕️' },
];

export const mockFeaturedCreators = [
  { ...mockUsers[0], postsCount: 234, engagement: 12450 },
  { ...mockUsers[2], postsCount: 189, engagement: 9870 },
  { ...mockUsers[4], postsCount: 256, engagement: 15620 },
  { ...mockUsers[3], postsCount: 145, engagement: 8940 },
];

export const userStats = {
  totalPosts: 234,
  totalNotes: 12,
  totalCourses: 3,
  enrolledCourses: 2,
  completedCourses: 1,
  quizzesTaken: 156,
  totalPoints: 32100,
  currentStreak: 72,
  level: 'Intermediate',
  badges: ['Early Adopter', 'Quiz Master', 'Content Creator', 'Community Helper'],
  studyHours: 450,
  certificates: 3,
};
